# Generated by Django 3.0.2 on 2020-04-03 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_people'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity_max', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('categ', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=100)),
                ('gst_no', models.IntegerField()),
                ('categ', models.CharField(max_length=100)),
                ('isverify', models.IntegerField()),
                ('lat', models.FloatField()),
                ('loc', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellershop.Item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.People')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellershop.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellershop.Shop'),
        ),
    ]
