# Generated by Django 3.0.2 on 2020-04-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellershop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categ',
        ),
    ]
