# Generated by Django 2.2.4 on 2020-04-03 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_zoneadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoneadmin',
            name='aadharno',
        ),
        migrations.RemoveField(
            model_name='zoneadmin',
            name='lastloc',
        ),
        migrations.RemoveField(
            model_name='zoneadmin',
            name='tag',
        ),
    ]
