# Generated by Django 2.2.4 on 2020-04-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=100)),
                ('hospitalno', models.CharField(max_length=15)),
                ('lat', models.FloatField()),
                ('loc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacyname', models.CharField(max_length=100)),
                ('pharmacyno', models.CharField(max_length=15)),
                ('lat', models.FloatField()),
                ('loc', models.FloatField()),
            ],
        ),
    ]
